# Generated by Django 3.1.1 on 2020-10-18 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('image', models.ImageField(upload_to='gallery/%Y/%m/%d')),
                ('is_shown', models.BooleanField(default=False)),
            ],
        ),
    ]
