# Generated by Django 3.1.1 on 2020-10-07 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='recipes/%Y/%m/%d')),
                ('score', models.PositiveIntegerField(default=0)),
                ('ingredients', models.TextField()),
                ('instructions', models.TextField()),
                ('is_showcased', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_recipe', to='profiles.userprofile')),
            ],
        ),
    ]
