# Generated by Django 3.1.1 on 2020-10-18 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('recipes', '0002_recipe_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='saved_by_users',
            field=models.ManyToManyField(to='profiles.UserProfile'),
        ),
    ]
